[workspace]
authors = ["Olivera Olejar <oliverolejar@icloud.com>"]
channels = ["conda-forge", "bioconda"]
name = "spimquant-output-analysis"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
pandas = ">=3.0.5,<4"
ipykernel = ">=7.3.0,<8"
nibabel = ">=5.4.2,<6"
pyarrow = ">=25.0.0,<26"
zarr = ">=3.3.0,<4"
matplotlib = ">=3.11.1,<4"
pillow = ">=12.3.0,<13"
nbconvert = ">=7.17.1,<8"
scipy = ">=1.18.1,<2"
statsmodels = ">=0.15.0,<0.16"
